export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const SEARCH_MOVIES_RESULTS = 'SEARCH_MOVIES_RESULTS';
export const ADD_MOVIE_TO_PLAYLIST = 'ADD_MOVIE_TO_PLAYLIST';
export const GET_NOW_PLAYING = 'GET_NOW_PLAYING';